name: los_pollos_hermanos
description: "Projeto Restaurante."
publish_to: 'none'
version: 0.2.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  device_preview: ^1.2.0
  image_network: ^2.5.4+1
  get_it: ^8.0.0
  shared_preferences: ^2.0.13 
  logger: ^1.4.0 
  path_provider: ^2.1.4
  video_player: ^2.4.5
  audioplayers: ^6.1.0
  collection: ^1.16.0
  file_picker: ^8.0.3
  http: ^1.0.0
  just_audio: ^0.9.18
  get: ^4.6.6
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0
  provider: ^6.1.2
  intl: ^0.19.0
  flutter_dotenv: ^5.0.2

dev_dependencies:
  audioplayers_platform_interface: ^7.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets: 
    - lib/images/
    - lib/videos/
    - lib/audios/
    - lib/fonts/
    - .env

  fonts:
    - family: CarnevaleeFreakshow
      fonts:
        - asset: lib/fonts/CarnevaleeFreakshow.ttf

