// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;



final FirebaseOptions web = FirebaseOptions(
  apiKey: dotenv.env['API_KEY']!,
  appId: dotenv.env['APP_ID']!,
  messagingSenderId: dotenv.env['MESSAGING_SENDER_ID']!,
  projectId: dotenv.env['PROJECT_ID']!,
  authDomain: dotenv.env['AUTH_DOMAIN']!,
  storageBucket: dotenv.env['STORAGE_BUCKET']!,
);

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }
/*
  /// The default [FirebaseOptions] for web PORTUGUESE BRAZILIAN version.
  /// env.
   
  API_KEY=AIzaSyC7Z9TjFcEeocGCbEscOuILKCojAYIU4vA
  APP_ID=1:901751865339:web:09e2bf5498f5111904955e
  MESSAGING_SENDER_ID=901751865339
  PROJECT_ID=cardapio-los-pollos-hermanos
  AUTH_DOMAIN=cardapio-los-pollos-hermanos.firebaseapp.com
  STORAGE_BUCKET=cardapio-los-pollos-hermanos.firebasestorage.app

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7Z9TjFcEeocGCbEscOuILKCojAYIU4vA',
    appId: '1:901751865339:web:09e2bf5498f5111904955e',
    messagingSenderId: '901751865339',
    projectId: 'cardapio-los-pollos-hermanos',
    authDomain: 'cardapio-los-pollos-hermanos.firebaseapp.com',
    storageBucket: 'cardapio-los-pollos-hermanos.firebasestorage.app',
  );

  /// The default [FirebaseOptions] for web ENGLISH version. 
  /// env. 
  
  API_KEY=AIzaSyCMs5QIe5cBLk3wmtHS67Ys53ZyprHjwPA
  APP_ID=1:1066069085654:web:718c6c2e325672b5e32877
  MESSAGING_SENDER_ID=1066069085654
  PROJECT_ID=los-pollos-hermanos-restaurant
  AUTH_DOMAIN=los-pollos-hermanos-restaurant.firebaseapp.com
  STORAGE_BUCKET=los-pollos-hermanos-restaurant.firebasestorage.app

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyCMs5QIe5cBLk3wmtHS67Ys53ZyprHjwPA",
    authDomain: "los-pollos-hermanos-restaurant.firebaseapp.com",
    projectId: "los-pollos-hermanos-restaurant",
    storageBucket: "los-pollos-hermanos-restaurant.firebasestorage.app",
    messagingSenderId: "1066069085654",
    appId: "1:1066069085654:web:718c6c2e325672b5e32877"
    );
    
};
*/

}